
package com.TangTangQing.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MidServiceSoap", targetNamespace = "http://TTQMid.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MidServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://TTQMid.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://TTQMid.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://TTQMid.org/", className = "com.mid.service.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://TTQMid.org/", className = "com.mid.service.HelloWorldResponse")
    public String helloWorld();

    /**
     * ��֪ͨ�����е���Ч������뵽�����м����
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "APP_PushNotification_Message_ToMid", action = "http://TTQMid.org/APP_PushNotification_Message_ToMid")
    @WebResult(name = "APP_PushNotification_Message_ToMidResult", targetNamespace = "http://TTQMid.org/")
    @RequestWrapper(localName = "APP_PushNotification_Message_ToMid", targetNamespace = "http://TTQMid.org/", className = "com.mid.service.APPPushNotificationMessageToMid")
    @ResponseWrapper(localName = "APP_PushNotification_Message_ToMidResponse", targetNamespace = "http://TTQMid.org/", className = "com.mid.service.APPPushNotificationMessageToMidResponse")
    public String appPushNotificationMessageToMid();

    /**
     * ������-�û����͹�ϵ��������δ���͵�������������м����
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "APP_PushNotification_Receiver_ToMid", action = "http://TTQMid.org/APP_PushNotification_Receiver_ToMid")
    @WebResult(name = "APP_PushNotification_Receiver_ToMidResult", targetNamespace = "http://TTQMid.org/")
    @RequestWrapper(localName = "APP_PushNotification_Receiver_ToMid", targetNamespace = "http://TTQMid.org/", className = "com.mid.service.APPPushNotificationReceiverToMid")
    @ResponseWrapper(localName = "APP_PushNotification_Receiver_ToMidResponse", targetNamespace = "http://TTQMid.org/", className = "com.mid.service.APPPushNotificationReceiverToMidResponse")
    public String appPushNotificationReceiverToMid();

    /**
     * ���·�����֪ͨ���漰�û������ϵ�����м��
     * 
     * @param messageID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "APP_PushNotification_OneNotice_ToMid", action = "http://TTQMid.org/APP_PushNotification_OneNotice_ToMid")
    @WebResult(name = "APP_PushNotification_OneNotice_ToMidResult", targetNamespace = "http://TTQMid.org/")
    @RequestWrapper(localName = "APP_PushNotification_OneNotice_ToMid", targetNamespace = "http://TTQMid.org/", className = "com.mid.service.APPPushNotificationOneNoticeToMid")
    @ResponseWrapper(localName = "APP_PushNotification_OneNotice_ToMidResponse", targetNamespace = "http://TTQMid.org/", className = "com.mid.service.APPPushNotificationOneNoticeToMidResponse")
    public String appPushNotificationOneNoticeToMid(
        @WebParam(name = "messageID", targetNamespace = "http://TTQMid.org/")
        int messageID);

    /**
     * �м����������Ϣ����������ݿ�ͬ��
     * 
     * @param offlineMsgUserRemoveCache
     * @return
     *     returns int
     */
    @WebMethod(operationName = "APP_PushNotification_Receiver_UpdatePushState", action = "http://TTQMid.org/APP_PushNotification_Receiver_UpdatePushState")
    @WebResult(name = "APP_PushNotification_Receiver_UpdatePushStateResult", targetNamespace = "http://TTQMid.org/")
    @RequestWrapper(localName = "APP_PushNotification_Receiver_UpdatePushState", targetNamespace = "http://TTQMid.org/", className = "com.mid.service.APPPushNotificationReceiverUpdatePushState")
    @ResponseWrapper(localName = "APP_PushNotification_Receiver_UpdatePushStateResponse", targetNamespace = "http://TTQMid.org/", className = "com.mid.service.APPPushNotificationReceiverUpdatePushStateResponse")
    public int appPushNotificationReceiverUpdatePushState(
        @WebParam(name = "offlineMsgUserRemoveCache", targetNamespace = "http://TTQMid.org/")
        String offlineMsgUserRemoveCache);

}
