
package com.TangTangQing.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * �����м������
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MidService", targetNamespace = "http://TTQMid.org/", wsdlLocation = "file:/F:/MidService.wsdl")
public class MidService
    extends Service
{

    private final static URL MIDSERVICE_WSDL_LOCATION;
    private final static WebServiceException MIDSERVICE_EXCEPTION;
    private final static QName MIDSERVICE_QNAME = new QName("http://TTQMid.org/", "MidService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8050/MidService.asmx");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MIDSERVICE_WSDL_LOCATION = url;
        MIDSERVICE_EXCEPTION = e;
    }

    public MidService() {
        super(__getWsdlLocation(), MIDSERVICE_QNAME);
    }

    public MidService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MIDSERVICE_QNAME, features);
    }

    public MidService(URL wsdlLocation) {
        super(wsdlLocation, MIDSERVICE_QNAME);
    }

    public MidService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MIDSERVICE_QNAME, features);
    }

    public MidService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MidService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MidServiceSoap
     */
    @WebEndpoint(name = "MidServiceSoap")
    public MidServiceSoap getMidServiceSoap() {
        return super.getPort(new QName("http://TTQMid.org/", "MidServiceSoap"), MidServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MidServiceSoap
     */
    @WebEndpoint(name = "MidServiceSoap")
    public MidServiceSoap getMidServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://TTQMid.org/", "MidServiceSoap"), MidServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MIDSERVICE_EXCEPTION!= null) {
            throw MIDSERVICE_EXCEPTION;
        }
        return MIDSERVICE_WSDL_LOCATION;
    }

}
